title:              YeolLog
email:              migle.sy@gmail.com
description:        Su-yeol's Blog for Study
author:             Su-yeol
baseurl:            ""
url:                "https://yeollog.github.io"

# Social Profiles
twitter_username:   yeollog
github_username:    yeollog
facebook_username:  suyeol.yu.35
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
